"use client";
import Head from "next/head";
import { signIn } from "next-auth/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h2>Office 365 login in Next.js using NextAuth.js </h2>
          <button
            onClick={() => {
              signIn(
                "azure-ad",
                { callbackUrl: "/dashboard" },
                { prompt: "login" }
              );
            }}
          >
            Log in
          </button>
        </div>
      </main>
    </>
  );
}
